#!/bin/bash

mkdir build

#build euphony and eusolver
pushd recommend
git clone --recursive https://gitee.com/jiry_2/my-euphony.git
pushd my-euphony
./build
popd
popd


#build esolver
pushd recommend/esolver
mkdir thirdparty/libeusolver/build
./scripts/build.sh
popd


#get gurobi
echo -n "enter Gurobi path (.../gurobi911/linux64):  "
read gurobipath
sgurobipath=${gurobipath//\//\\\/}
sed -i "s/GUROBIPATH/${sgurobipath}/g" src/CMakeLists.txt



#get z3
git clone https://gitee.com/jiry_2/z3.git
pushd z3
python scripts/mk_make.py
pushd build
z3path=`pwd`
echo ${z3path}
make -j 8
sudo make install
popd
popd
sz3path=${z3path//\//\\\/}
sed -i "s/Z3PATH/${sz3path}/g" src/CMakeLists.txt



#build source
pushd src
path=`pwd`
spath=${path//\//\\\/}
sed -i "s/SOURCEPATH/\"${spath}\"/g" basic/config.cpp
popd

pushd build
cmake ../src
make
