#!/bin/bash

mkdir build

: '
#build euphony
pushd recommend/euphony
./build
popd

#build eusolver
pushd recommend/eusolver
mkdir thirdparty/libeusolver/build
./scripts/build.sh
popd
'

#build esolver
pushd recommend/esolver
mkdir thirdparty/libeusolver/build
./scripts/build.sh
popd




#get gurobi
echo -n "enter Gurobi path (.../gurobi911/linux64):  "
read gurobipath
sgurobipath=${gurobipath//\//\\\/}
sed -i "s/GUROBIPATH/${sgurobipath}/g" src/CMakeLists.txt



#get z3
pushd z3
python scripts/mk_make.py
pushd build
z3path=`pwd`
echo ${z3path}
make
popd
popd
sz3path=${z3path//\//\\\/}
sed -i "s/Z3PATH/${sz3path}/g" src/CMakeLists.txt



#build source
pushd src
path=`pwd`
spath=${path//\//\\\/}
sed -i "s/SOURCEPATH/\"${spath}\"/g" basic/config.cpp
popd

pushd build
cmake ../src
make
