#!/bin/bash

mkdir build

'''
#build euphony
pushd recommend/euphony
./build
popd


#build esolver
pushd recommend/esolver
mkdir thirdparty/libeusolver/build
./scripts/build.sh
popd
'''


#build eusolver
pushd recommend/eusolver
mkdir thirdparty/libeusolver/build
./scripts/build.sh
popd
'''
#get gurobi
echo -n "enter Gurobi path (.../gurobi911/linux64):  "
read gurobipath
sgurobipath=${gurobipath//\//\\\/}
sed -i "s/GUROBIPATH/${sgurobipath}/g" src/CMakeLists.txt
echo src/CMakeLists.txt

#get z3
echo -n "enter Z3 path (.../z3/build):  "
read z3path
sz3path=${z3path//\//\\\/}
sed -i "s/Z3PATH/${sz3path}/g" src/CMakeLists.txt
echo src/CMakeLists.txt

#build source
pushd src
path=`pwd`
spath=${path//\//\\\/}
sed -i "s/SOURCEPATH/\"${spath}\"/g" basic/config.cpp
popd

pushd build
cmake ../src
make
'''